# Generated by Django 5.0 on 2024-09-08 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="guid",
            new_name="id",
        ),
    ]
